




GET http://localhost:3000/states/


###

POST http://localhost:3000/login
content-type:application/json

{
  "username": "christopher_phillips",
  "password": "christy@123"
}

###


GET http://localhost:3000/states/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzA4MDk1OTkwfQ.vUH6SfBNxiN751JNQPfJGoBDMOhYAr6qR4gcyKhAQLo

###

GET http://localhost:3000/districts/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzA4MDk1OTkwfQ.vUH6SfBNxiN751JNQPfJGoBDMOhYAr6qR4gcyKhAQLo

###



POST http://localhost:3000/districts
content-type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzA4MDk1OTkwfQ.vUH6SfBNxiN751JNQPfJGoBDMOhYAr6qR4gcyKhAQLo


{
  "districtName": "Bagalkot",
  "stateId": 3,
  "cases": 2323,
  "cured": 2000,
  "active": 315,
  "deaths": 8
}


###

PUT http://localhost:3000/districts/4
content-type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzA4MDk1OTkwfQ.vUH6SfBNxiN751JNQPfJGoBDMOhYAr6qR4gcyKhAQLo



{
  "districtName": "Nadia",
  "stateId": 3,
  "cases": 9628,
  "cured": 6524,
  "active": 3000,
  "deaths": 104
}

###

DELETE http://localhost:3000/districts/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzA4MDk1OTkwfQ.vUH6SfBNxiN751JNQPfJGoBDMOhYAr6qR4gcyKhAQLo

###


GET http://localhost:3000/states/4/stats/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzA4MDk1OTkwfQ.vUH6SfBNxiN751JNQPfJGoBDMOhYAr6qR4gcyKhAQLo
 


